AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: >-
  A Angular-Lambda Bridge
Resources:
  AngularUniversalRenderer:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: ./dist
      Handler: lambda.handler
      Runtime: nodejs8.10
      Description: >-
        Serves static files and pre-renders Angular endpoints
      MemorySize: 192
      Timeout: 30
      Policies:
        - Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
      Events:
        ApiServerlessRequest:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY

